/**
 * Document Export Utilities (Markdown, Plain Text, Printable View, JSON)
 */

import { LegalDocument } from '../types/legal';

export function exportDocumentAnalysisMarkdown(doc: LegalDocument): string {
  const lines: string[] = [];

  lines.push(`# Legal Analysis Report: ${doc.name}`);
  lines.push(`Generated by LegalLens AI on ${new Date().toLocaleDateString('en-IN')}`);
  lines.push('');
  lines.push('> **DISCLAIMER:** This report provides automated information and document intelligence. It does NOT constitute formal legal advice. Please consult an advocate before making contractual commitments.');
  lines.push('');

  if (doc.summary) {
    lines.push('## Executive Summary');
    lines.push(doc.summary.executiveSummary);
    lines.push('');
    lines.push(`- **Overall Risk Score:** ${doc.summary.overallRiskScore} / 100 (${doc.summary.overallRiskSeverity.toUpperCase()})`);
    lines.push(`- **Total Clauses Identified:** ${doc.summary.totalClauses}`);
    lines.push(`- **Critical Red Flags:** ${doc.summary.criticalRisksCount}`);
    lines.push(`- **High Risk Cautions:** ${doc.summary.highRisksCount}`);
    lines.push('');
  }

  if (doc.risks && doc.risks.length > 0) {
    lines.push('## Critical Risks & Red Flags');
    doc.risks.forEach((risk, idx) => {
      lines.push(`### ${idx + 1}. [${risk.severity.toUpperCase()}] ${risk.title}`);
      lines.push(`- **Section Reference:** ${risk.sectionPath}`);
      lines.push(`- **Source Quote:** _"${risk.sourceQuote}"_`);
      lines.push(`- **Practical Impact:** ${risk.practicalImpact}`);
      lines.push(`- **Recommended Action:** ${risk.recommendedAction}`);
      if (risk.suggestedNegotiationRedline) {
        lines.push(`- **Suggested Redline:** \`${risk.suggestedNegotiationRedline}\``);
      }
      if (risk.legalBasisOrJurisdictionNotice) {
        lines.push(`- **Legal Context:** ${risk.legalBasisOrJurisdictionNotice}`);
      }
      lines.push('');
    });
  }

  if (doc.summary?.checklist && doc.summary.checklist.length > 0) {
    lines.push('## Actionable Next Steps Checklist');
    doc.summary.checklist.forEach((item) => {
      const mark = item.completed ? '[x]' : '[ ]';
      lines.push(`- ${mark} **[${item.priority.toUpperCase()}]** ${item.action} *(Ref: ${item.sourceSection || 'General'})*`);
    });
    lines.push('');
  }

  if (doc.summary?.lawyerPrepGuide && doc.summary.lawyerPrepGuide.length > 0) {
    lines.push('## Lawyer Consultation Brief');
    doc.summary.lawyerPrepGuide.forEach((prep, idx) => {
      lines.push(`### Question ${idx + 1}: ${prep.suggestedQuestion}`);
      lines.push(`- **Topic:** ${prep.topic}`);
      lines.push(`- **Target Clause:** ${prep.specificClauseReference}`);
      lines.push(`- **Why Ask:** ${prep.contextWhyAsk}`);
      lines.push(`- **Goal:** ${prep.targetOutcome}`);
      if (prep.documentsToBring?.length) {
        lines.push(`- **Bring to Meeting:** ${prep.documentsToBring.join(', ')}`);
      }
      lines.push('');
    });
  }

  return lines.join('\n');
}

export function downloadFile(content: string, fileName: string, mimeType = 'text/markdown') {
  const blob = new Blob([content], { type: `${mimeType};charset=utf-8;` });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.setAttribute('href', url);
  link.setAttribute('download', fileName);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
